language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


install:
# - docker-compose -f final-project/udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel
# - docker-compose -f final-project/udacity-c3-deployment/docker/docker-compose-build.yaml push 

  - sed -i -e 's|ENV_POSTGRESS_USERNAME|'"${ENV_POSTGRESS_USERNAME}"'|g' final-project/udacity-c3-deployment/k8s/env-secret.yaml
  - sed -i -e 's|ENV_POSTGRESS_PASSWORD|'"${ENV_POSTGRESS_PASSWORD}"'|g' final-project/udacity-c3-deployment/k8s/env-secret.yaml
  - sed -i -e 's|ENV_POSTGRESS_DB|'"${ENV_POSTGRESS_DB}"'|g' final-project/udacity-c3-deployment/k8s/env-secret.yaml
  - sed -i -e 's|ENV_POSTGRESS_HOST|'"${ENV_POSTGRESS_HOST}"'|g' final-project/udacity-c3-deployment/k8s/env-secret.yaml
  - sed -i -e 's|ENV_AWS_REGION|'"${ENV_AWS_REGION}"'|g' final-project/udacity-c3-deployment/k8s/env-secret.yaml
  - sed -i -e 's|ENV_AWS_PROFILE|'"${ENV_AWS_PROFILE}"'|g' final-project/udacity-c3-deployment/k8s/env-secret.yaml
  - sed -i -e 's|ENV_AWS_BUCKET|'"${ENV_AWS_BUCKET}"'|g' final-project/udacity-c3-deployment/k8s/env-secret.yaml
  - sed -i -e 's|ENV_JWT_SECRET|'"${ENV_JWT_SECRET}"'|g' final-project/udacity-c3-deployment/k8s/env-secret.yaml

  - sed -i -e 's|ENV_AWS_CREDENTIALS|'"${ENV_AWS_CREDENTIALS}"'|g' final-project/udacity-c3-deployment/k8s/aws-secret.yaml

  - sed -i -e 's|ENV_KUBE_CA_CERT|'"${ENV_KUBE_CA_CERT}"'|g' final-project/udacity-c3-deployment/kube/kubeconfig.yaml
  - sed -i -e 's|ENV_KUBE_ENDPOINT|'"${ENV_KUBE_ENDPOINT}"'|g' final-project/udacity-c3-deployment/kube/kubeconfig.yaml
  - sed -i -e 's|ENV_CLUSTER_NAME|'"${ENV_CLUSTER_NAME}"'|g' final-project/udacity-c3-deployment/kube/kubeconfig.yaml
  - sed -i -e 's|ENV_CLUSTER_REGION|'"${ENV_CLUSTER_REGION}"'|g' final-project/udacity-c3-deployment/kube/kubeconfig.yaml
  - sed -i -e 's|ENV_CLUSTER_USER|'"${ENV_CLUSTER_USER}"'|g' final-project/udacity-c3-deployment/kube/kubeconfig.yaml
  - sed -i -e 's|ENV_CLUSTER_SIMPLE_NAME|'"${ENV_CLUSTER_SIMPLE_NAME}"'|g' final-project/udacity-c3-deployment/kube/kubeconfig.yaml

  - docker run -v "$(pwd)/final-project/udacity-c3-deployment/k8s/:/app/k8s/" -v "$(pwd)/final-project/udacity-c3-deployment/kube/:/app/kube/" -e AWS_ACCESS_KEY_ID=${ENV_AWS_TRAVIS_ACCESS_KEY} -e AWS_SECRET_ACCESS_KEY=${ENV_AWS_TRAVIS_SECRET_ACCESS_KEY} -e AWS_PROFILE="default" marcecardozo/kubectl-eks kubectl --kubeconfig=/app/kube/kubeconfig.yaml apply -f /app/k8s/

