apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ENV_KUBE_CA_CERT
    server: ENV_KUBE_ENDPOINT
  name: ENV_CLUSTER_NAME
contexts:
- context:
    cluster: ENV_CLUSTER_NAME
    user: ENV_CLUSTER_USER
  name: ENV_CLUSTER_USER
current-context: ENV_CLUSTER_USER
kind: Config
preferences: {}
users:
- name: ENV_CLUSTER_USER
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - ENV_CLUSTER_SIMPLE_NAME
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: ENV_CLUSTER_REGION